# Basic build settings
[build]
  base    = ""              # Base directory where your code is located (if not in the root)
  publish = "public"        # Directory to publish (often 'public' or 'dist')
  command = "npm run build" # Command to build your site

# Redirects
[[redirects]]
  from = "/old-path"
  to = "/new-path"
  status = 301
  force = true

[[redirects]]
  from = "/another-old-path/*"
  to = "/another-new-path/:splat"
  status = 301
  force = true

# Headers
[[headers]]
  for = "/*"
  [headers.values]
    X-Frame-Options = "DENY"
    X-XSS-Protection = "1; mode=block"
    X-Content-Type-Options = "nosniff"
    Referrer-Policy = "same-origin"

[[headers]]
  for = "/specific-path"
  [headers.values]
    Cache-Control = "public, max-age=31536000"

# Plugins
[[plugins]]
  package = "@netlify/plugin-lighthouse"
  [plugins.inputs]
    threshold = 90
